#+TITLE: Emacs Configuration
#+AUTHOR: William Neville
#+EMAIL: william@neville.com
#+OPTIONS: toc:nil num:nil

* Introduction

Almost all of this lifted from other, more sophisticated Emacs users. Those of 
note linked below:
[[https://github.com/abrochard/emacs-config][abrochard]]
[[https://github.com/hrs/dotfiles/tree/master/emacs/.emacs.d][hrs]]

* Configure =use-package=

Package installation and configuration done via =use-package=. See =init.el= for
baseline configuration. 

Ensure that =use-package= installs package if not already installed.

#+BEGIN_SRC emacs-lisp
  (setq use-package-always-ensure t)
#+END_SRC

Always compile packages, and use the newest version available.

#+BEGIN_SRC emacs-lisp
  (use-package auto-compile
    :config (auto-compile-on-load-mode))

  (setq load-prefer-newer t)
#+END_SRC

* UI/UX
I only use GUI emacs - these are baseline modifications.
** Windows, Frames and Buffers
*** Disable noisy emacs GUI elements
#+BEGIN_SRC emacs-lisp
(menu-bar-mode -1)
(toggle-scroll-bar -1)
(tool-bar-mode -1)
#+END_SRC
*** If OS X "bonks" at me one more time
#+BEGIN_SRC emacs-lisp
(setq ring-bell-function 'ignore)
#+END_SRC
*** Start in full screen by default
#+BEGIN_SRC emacs-lisp
(toggle-frame-maximized)
#+END_SRC
*** Scratch buffer empty, please.
#+BEGIN_SRC emacs-lisp
(setq initial-scratch-message nil)
#+END_SRC
*** Inhibit startup message.
#+BEGIN_SRC emacs-lisp
(setq inhibit-startup-message t)
#+END_SRC
*** Global line numbers
#+BEGIN_SRC emacs-lisp
(global-linum-mode t)
#+END_SRC
** UI
*** Theme
Currently I'm digging gruvbox
#+BEGIN_SRC emacs-lisp
(use-package gruvbox-theme
  :defer t
  :init (load-theme 'gruvbox-dark-medium t))
#+END_SRC
*** All the icons!
all-the-icons makes neotree look cooler. Workaround to install fonts if not already installed.
#+BEGIN_SRC emacs-lisp
(use-package all-the-icons
  :config (lambda ()  ;; workaround to only install fonts if not already installed
            (unless (member "all-the-icons" (font-family-list))
              (all-the-icons-install-fonts t))))
#+END_SRC
** UX
*** Ask for confirmation before quitting
The number of times I've fat fingered C-x C-c...
#+BEGIN_SRC emacs-lisp
(setq confirm-kill-emacs 'y-or-n-p)
#+END_SRC
*** Accept "y" and "n" in place of "yes" and "no"
#+BEGIN_SRC emacs-lisp
(fset 'yes-or-no-p 'y-or-n-p)
#+END_SRC
*** Auto-indent on RET rather than just C-j
#+BEGIN_SRC emacs-lisp
(define-key global-map (kbd "RET") 'newline-and-indent)
#+END_SRC
* Personal Information
#+BEGIN_SRC emacs-lisp
  (setq user-full-name "William Neville"
        user-mail-address "william@neville.com"
        calendar-latitude 40.72
        calendar-longitude -73.99
        calendar-location-name "New York, NY")
#+END_SRC

* Version Control
** Magit

You can basically do everything from magit-status.

#+BEGIN_SRC emacs-lisp
(use-package magit
  :bind ("C-x g" . magit-status))
#+END_SRC

** Utility Functions
*** Git blame
#+BEGIN_SRC emacs-lisp
(defun git-blame-line ()
  "Runs `git blame` on the current line and
   adds the commit id to the kill ring"
  (interactive)
  (let* ((line-number (save-excursion
                        (goto-char (point-at-bol))
                        (+ 1 (count-lines 1 (point)))))
         (line-arg (format "%d,%d" line-number line-number))
         (commit-buf (generate-new-buffer "*git-blame-line-commit*")))
    (call-process "git" nil commit-buf nil 
                  "blame" (buffer-file-name) "-L" line-arg)
    (let* ((commit-id (with-current-buffer commit-buf
                        (buffer-substring 1 9)))
           (log-buf (generate-new-buffer "*git-blame-line-log*")))
      (kill-new commit-id)
      (call-process "git" nil log-buf nil 
                    "log" "-1" "--pretty=%h   %an   %s" commit-id)
      (with-current-buffer log-buf
        (message "Line %d: %s" line-number (buffer-string)))
      (kill-buffer log-buf))
    (kill-buffer commit-buf)))
#+END_SRC

* Org Mode
** Set environment

Base configuration.

#+BEGIN_SRC emacs-lisp
(use-package org
  :bind (("C-c l" . org-store-link)
         ("C-c a" . org-agenda)))
#+END_SRC

I like to log when tasks were completed.

#+BEGIN_SRC emacs-lisp
(setq org-log-done t)
#+END_SRC

I keep all my org stuff in Dropbox. Experimenting with =beorg= on iOS,
so this behooves me.

#+BEGIN_SRC emacs-lisp
(setq org-agenda-files '("~/Dropbox/org"))
#+END_SRC

** Capture Templates

#+BEGIN_SRC emacs-lisp
  (setq org-capture-templates
        '(("t" "Todo" entry
           (file+headline "~/Dropbox/org/gtd.org" "Tasks")
           "* TODO %?\n %i\n %a")
           ("e" "Emacs idea/project" entry
           (file+headline "~/Dropbox/org/emacs-ideas.org" "Ideas")
           "* %?\n %T")))
#+END_SRC

* Unsorted
#+BEGIN_SRC emacs-lisp
(use-package better-defaults)
(use-package elpy)
(use-package jedi)
(use-package yaml-mode)
(use-package dockerfile-mode)
(use-package restclient)
(use-package fish-mode)
(use-package fill-column-indicator)
(use-package elfeed
  :bind ("C-x w" . elfeed))
(use-package exec-path-from-shell)  ;; if on Mac
(use-package projectile)
(use-package neotree)
(use-package json-mode)

;; 2 space indent for shell scripts
(setq sh-basic-offset 2)

(when (memq window-system '(mac ns))
  (exec-path-from-shell-initialize)
  (exec-path-from-shell-copy-envs
   '("PATH")))

(setq elfeed-feeds
      '(("http://xkcd.com/rss.xml" comic)
	("https://www.smbc-comics.com/rss.php" comic)
	("http://reddit.com/r/emacs/.rss" emacs)
	("http://planet.emacsen.org/atom.xml" emacs)
	("http://pragmaticemacs.com/feed/" emacs)
	("http://rss.slashdot.org/Slashdot/slashdotMain" tech)
	("https://www.joelonsoftware.com/feed/" tech)
	("http://news.mit.edu/rss/topic/computers" tech)
	("https://news.ycombinator.com/rss" tech)))
(setq-default elfeed-search-filter "@1-week-ago +unread")

;; Set neotree theme
(setq neo-theme (if (display-graphic-p) 'icons 'arrow))

;; Enable elpy
(elpy-enable)

;; Treat things in snake_case as one word when we're in Python mode
(add-hook 'python-mode-hook 'superword-mode)

;; Fill column indicator config
(setq fci-rule-column 100)
(setq fci-rule-width 1)
(setq fci-rule-color "purple")
(add-hook 'python-mode-hook 'fci-mode)

(defvar-local company-fci-mode-on-p nil)

(defun company-turn-off-fci (&rest ignore)
  (when (boundp 'fci-mode)
    (setq company-fci-mode-on-p fci-mode)
    (when fci-mode (fci-mode -1))))

(defun company-maybe-turn-on-fci (&rest ignore)
  (when company-fci-mode-on-p (fci-mode 1)))

(add-hook 'company-completion-started-hook 'company-turn-off-fci)
(add-hook 'company-completion-finished-hook 'company-maybe-turn-on-fci)
(add-hook 'company-completion-cancelled-hook 'company-maybe-turn-on-fci)

;; Project specific find-file configuration
(defun my-setup-develop-environment ()
  (interactive)
  ;; When searching files in the olympus directory, ignore virtualenv dir
  (when (ffip-current-full-filename-match-pattern-p "olympus")
    (add-to-list 'ffip-prune-patterns "*/env")))
(add-hook 'prog-mode-hook 'my-setup-develop-environment)
#+END_SRC
